version: '3'

services:
  postgres:
    image: postgres:13.3
    container_name: "tinker-postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - local
  tinker-api:
    build: .
    image: tinker-api:v1
    container_name: "tinker-api"
    environment:
      NODE_ENV: test
    ports:
      - 4040:4040
    networks:
      - local
networks:
  local:
    driver: bridge