FROM node:14.17.0-alpine

WORKDIR /app

COPY .env /app

COPY config/ /app/config/
COPY package.json /app
COPY yarn.lock /app

RUN yarn

COPY models/ app/models
COPY src/ /app/src/

EXPOSE 4040

CMD ["yarn", "start"]